apiVersion: apps/v1
kind: Deployment
metadata:
  name: zoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zoperator
  template:
    metadata:
      labels:
        name: zoperator
    spec:
      serviceAccountName: zoperator
      containers:
        - name: zoperator
          image: "zadara/zoperator:0.1.0"
          command:
            # note: this overrides ENTRYPOINT defined in Docker image
            - zoperator
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "zoperator"
          volumeMounts:
            - name: config-dir
              mountPath: /etc/zoperator
      volumes:
        - name: config-dir
          configMap:
            name: zoperator-config-map
            optional: true
